### ISSUE TITLE
question: non typescript support

### ISSUE THREAD

**Issue by prescottprue** [bennycode/ts2esm#20]
Hey nice work! Had very similar thoughts about how this is needed. Wanted to ask if there is a plan support non TS files as well - feel free to close if out of scope (seems like it may be).

I ask because I created [a jscodeshift transform](https://github.com/prescottprue/jscodeshift-esm) to do this same thing for my projects (before I found ts2esm) which are mostly Typescript, but some are JS. Was thinking of just contributing here instead of maintaining a similar tool, but keeping JS support is unfortunately a must on my end.

If not no worries at all - In that case I'll keep a link to ts2esm in the transform docs so folks can be aware of their different options (we all just want to update to ESM at the end of the day 😆 )

**Comment by bennycode** [comment]
Hi @prescottprue and thank you for reaching out! the `ts2esm` tool is heavily based on `ts-morph`. It can manipulate TypeScript and JavaScript code, so it should be possible to adjust `.js` files. Do you want to give it a try with one of your sample projects?

**Comment by jason-ha** [comment]
I think the requested support means adding detection in convert.ts for
```json
{newExtension: '.js', suffix: '.js'},
{newExtension: '/index.js', suffix: '/index.js'},
```
and maybe
```json
{newExtension: '.js', suffix: '.jsx'},
```
I came across this in repo I am working with, but case was very narrow and I just fixed by hand.

**Comment by bennycode** [comment]
@prescottprue I just released v1.2.2 with the suggestions from @jason-ha. Can you please check if it fulfills your use-case?

**Comment by jason-ha** [comment]
I also found a case where .cjs was referenced. So .cjs and .mjs should probably be checked as well. Propose #30

**Comment by prescottprue** [comment]
With the .cjs extension I'm looking good on the first project I tried, but I'll need to check the others. Thanks for the quick turnaround

**Comment by bennycode** [comment]
Cool, have you had the chance to check the others?

**Comment by bennycode** [comment]
Since there hasn't been any update, I am assuming that the testing went well. 🤞
