### ISSUE TITLE
ts2esm does not support files of type `file_name.some_extension.ts'

### ISSUE THREAD

**Issue by nerdynomadd** [bennycode/ts2esm#29]
I'd like to start by expressing my gratitude for your project; it has been incredibly helpful in transitioning our monorepository from CJS to ESM, saving a significant amount of time.

However, I encountered a limitation regarding the handling of file names in your ts2esm tool. Our project uses a specific naming convention for files, such as foo.dto.ts, bar.error.ts, and baz.controller.ts, where a part of the file name indicates its business role like DTOs, Models, Controllers, Services, Repositories, etc. The current implementation in the convert.ts file of ts2esm doesn't seem to properly recognize and convert imports with these naming patterns.

To address this, I cloned the project and introduced a temporary solution. I added an authorizedExtensions array to check whether info.extension falls under this list during import checks. Although this workaround is effective, it might not be the most optimal solution.

I believe ts2esm could be enhanced to natively support these types of file names. I'm also willing and eager to contribute to the development of this feature if needed :).

**Comment by bennycode** [comment]
Hi @nerdynomadd and thank you for making me aware of this issue. Can you build a test case in [util.test.ts](https://github.com/bennycode/ts2esm/blob/v1.2.2/src/util.test.ts) which demonstrates the problem?

The main logic how files are discovered sits here:
https://github.com/bennycode/ts2esm/blob/7da417236fe86a31e4d65c90b3318e0f8f74adfb/src/convert.ts#L73-L77

Can you log the values for `info`? It would be interesting to see which path is generated based on `info.directory` and `info.normalized`.

Best,
Benny

**Comment by jason-ha** [comment]
I realized yesterday that this was the reason my jest.config.js file reference wasn't being fixed up after the .js support addition.
One thing that could help this project is to have a set of example unfixed files in a test directory. And then a clone with the fixed result. At test script could copy the unfixed over the fixed set, then run ts2esm over those files and expect that they are all back to expected result (no git diff). There are other test setups too.
