### ISSUE TITLE
Non-relative import rewrites

### ISSUE THREAD

**Issue by sedghi** [bennycode/ts2esm#60]
In my code base, i have these imports 

`import @kitware/vtk.js/Common/DataModel/PiecewiseFunction`

that should change to 

`import @kitware/vtk.js/Common/DataModel/PiecewiseFunction.js`

But seems like the ts2esm does not support it, can we have this working somehow as well?

Thanks

**Comment by bennycode** [comment]
Yes, let's make it work! 💪

I just have to add your test case here and fix it afterwards: https://github.com/bennycode/ts2esm/blob/v2.0.0/src/util/PathUtil.test.ts#L50

**Comment by sedghi** [comment]
Nothing, just it doesn't detect it should do it

**Comment by sedghi** [comment]
This is our repo if it help

https://github.com/cornerstonejs/cornerstone3D

**Comment by bennycode** [comment]
I looked up your repo and I think I figured out what is going on...

- `'@kitware/vtk.js/Common/DataModel/PiecewiseFunction'` is not a local file
- `'@kitware/vtk.js/Common/DataModel/PiecewiseFunction'` is also not the main entry of a module (like `'gl-matrix'`)
- That's why `ts2esm` should look up the path from the `node_modules` directory

This functionality isn't currently implemented, but I will add it to support your project. I appreciate that you're developing medical imaging software—health is paramount, and I'd be glad to contribute in any way I can. :)

**Comment by sedghi** [comment]
Thanks! You can check out our deployed app to play around with real medical data at https://viewer.ohif.org/. If you happen to have a DICOM file son your desktop, you can drag and drop it here: https://viewer.ohif.org/localbasic to view it.

**Comment by bennycode** [comment]
> Thanks! You can check out our deployed app to play around with real medical data at https://viewer.ohif.org/. If you happen to have a DICOM file son your desktop, you can drag and drop it here: https://viewer.ohif.org/localbasic to view it.

That's super cool! 👍 I just made a fix to `ts2esm`. Can you try v2.0.1 with your project and let me know if it works?

**Comment by bennycode** [comment]
Hey @sedghi & @JamesAPetts, did my update fix your ts2esm issues?

**Comment by sedghi** [comment]
So sorry for the delayed response, we tried it on Friday, and it worked like a charm.

Thanks again for fixing this promptly

**Comment by bennycode** [comment]
@sedghi thank you for the feedback! 

May I add to the README of my project that it is being used by the [Open Health Imaging Foundation](https://ohif.org/)? I would like to highlight your web imaging platform as it is both a noble project and technologically fascinating. 

Also, your tech stack appears to be very modern. Would you or someone on your team be interested in additional promotion through blog articles in TypeScript channels or podcasts? This might bring more attention to your goals and attract extra open source contributions.

Best,
Benny

**Comment by sedghi** [comment]
Yes, absolutely, feel free to add that. I can discuss it with our product manager, and they will get back to you. Should I use mail@bennycode.com for communication?

**Comment by bennycode** [comment]
Yes, please. I will list you in my Readme file and your product manager can contact me via mail@bennycode.com 😊
