### ISSUE TITLE
Using with JS files.

### ISSUE THREAD

**Issue by Redoxahmii** [bennycode/ts2esm#80]
There isn't really any clarity on how this works for JS file just a link pointing to an issue.
It asks for a tsconfig.json but as the project is not using typescript it does'nt have a tsconfig.
Is that required for it to work ?

**Comment by bennycode** [comment]
Hi @Redoxahmii, do you have an open source JavaScript project where you want to try `ts2esm`? We could use it for testing. 

TypeScript supports plain JavaScript through a [jsconfig.json](https://code.visualstudio.com/docs/languages/jsconfig) file.

**Comment by bennycode** [comment]
It has been successfully tested with plain JavaScript: https://github.com/bennycode/ts2esm/issues/20#issuecomment-1894702085
